index.js

Please double check, only written in GH editor 🙈

refactor: config key presence check

---

README.md
index.js
package.json
plugin.js

Add fire perf

---

index.d.ts
index.js
plugin.js

Adds support for Firebase Analytics in Nuxt-Fire.  I tried to follow the existing Nuxt-fire conventions when adding analytics. Let me know if any changes are needed, thanks!
Closes #40

Add support for Firebase Analytics.

---

plugin.js

It will add support for code splitting and will resolve #42 issue

add code splitting support

---

index.d.ts

Its just little changing and will resolve #45 issue

add firebase performance monitoring definition

---

docs/getting-started/README.md
docs/options/README.md
index.js
package.json
templates/firebase-messaging-sw.js

- Added first experimental feature to add the FCM service worker

Simplify firebase messaging init

---

packages/nuxt-fire/src/index.d.ts

Added types to [context.app](https://ja.nuxtjs.org/api/context/#-code-app-code-em-nuxtappoptions-em-) and [context.store](https://nuxtjs.org/api/context/#-code-store-code-a-href-https-vuex-vuejs-org-en-api-html-vuexstore-instance-properties-em-vuex-store-em-a-)

added types

---

packages/nuxt-fire/src/index.d.ts

Just thought this might be a helpful addition, feel free to reject.

fix (typescript): improve type augmentations

---

package.json
packages/nuxt-fire/package.json

[keywords](https://docs.npmjs.com/files/package.json#keywords) is an array of strings.

Fix npm package keywords

---

lib/module.js

i got error when i try to init firebase module without auth service because cannot access .ssr from undefined at line 44

check if auth exist

---

lib/module.js

Firebase SDK has current version inside module.
https://firebase.google.com/docs/reference/js/firebase#sdk_-version

refactor: 💡 use firebase sdk version

---

README.md

📝 Readme : this.$fireAuth instead of $this.Auth

---

docs/guide/getting-started/README.md
docs/guide/options/README.md
lib/module.js
lib/plugins/main.js
lib/templates/firebase-messaging-sw.js
types/index.d.ts

This is a partial implementation of #165 after the changes done in #174 
We still need to figure out how to implement `notificationTemplate`

Feat/messaging (incomplete)

---

docs/guide/options/README.md
lib/plugins/main.js
types/index.d.ts

Analytics can be disabled in development environment.
Added new option that will allow us to do that with the module.
Read: https://firebase.google.com/docs/analytics/configure-data-collection

feat(analytics): added collectionEnabled option to analytics

---

docs/content/en/index.md

Typo on index page

---

docs/content/en/service-options/auth.md
lib/plugins/services/auth.js

Add emulatorPort and emulatorHost options for using a local Authentication Emulator

---

docs/content/en/service-options/messaging.md

Just noticed this when going through the docs

Add missing comma

---

lib/module.js
lib/sw-templates/firebase-messaging-sw.js
types/index.d.ts

This is a *very* basic implementation, but it would be nice to have something like this setup.

feat(messaging sw): allow users to inject a string into the messaging sw

---

docs/content/en/service-options/storage.md
lib/plugins/services/storage.js
types/index.d.ts

Add storage emulators settings

feat: add storage emulators settings

---

README.md

chore: cleanup of latest notice

---

lib/utils/auth-ssr/ssr-auth-session-manager.js

fix the if and the or operator

some linting and styling

---

packages/docs/content/service-options/auth.md

There is a need for an example on how to actually do the login/sign in with Google or any other provider.

Added example for a provider
