- README.md
- package.json
- plugin.js
Add Providers which are missing within the instance of $fireAuth
Usage:
`loginWithGoogle() {
var provider = new this.$fireAuthProviders.GoogleAuthProvider();
this.$fireAuth.signInWithRedirect(provider);
}`
> Add fireAuthProviders

- plugin.js
This adds a check to ensure Firebase Messaging is supported in the current environment before instantiating it.  It fixes an issue with Safari throwing an Environment Not Supported exception which breaks app loading.
Adding this check allows our apps to actually load and work when using Safari. 
Closes #38
> Check if Firebase Messaging is supported.

- README.md
- index.d.ts
- plugin.js
Add Firebase Remote Config support to nuxt-fire and will resolve #48 issue
> add firebase remote config service

- packages/nuxt-fire/src/index.js
The path used on firebase-messaging-sw.js creation is not correct.
> fix firebase-messaging-sw.js path

- packages/docs/guide/getting-started/README.md
I was going through the docs and saw a broken link.
It now links to the config section of the options page.
> fixed broken link to config section

- docs/guide/helpers/README.md
Fixes the path to helpers in docs.
> Fix helpers path in docs, 'lib' instead of 'src'

- docs/tutorials/ssr/README.md
Missing ":" in the docs for firebase.
> fix: syntax on firebase module

- docs/guide/introduction/README.md
Git diff is not so obvious for a long single line, therefore I hereby leave a manual diff.
*Before*
```
If you wan't 
```
*After*
```
If you want 
```
> docs(guide/introduction): fix typo

- docs/guide/options/README.md
Analytics and Remote Config options descriptions were referencing Storage.
> docs(options): analytics and remote config description

- types/index.d.ts
@nuxtjs/firebase: 6.1.0
firebase: 7.16.1
nuxt: 2.13.3
this error is occurred.
```
505:18 Interface 'Response<ResBody>' incorrectly extends interface 'ServerResponse'.
Types of property 'locals' are incompatible.
Property 'user' is missing in type 'Record<string, any>' but required in type '{ user: FireAuthServerUser; }'.
503 | export type Send<ResBody = any, T = Response<ResBody>> = (body?: ResBody) => T;
504 | 
> 505 | export interface Response<ResBody = any> extends http.ServerResponse, Express.Response {
|                  ^
506 |     /**
507 |      * Set status `code`.
508 |      */
```
`locals` has changed from `any` to `Record<string, any>` in this PR.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46230
`idToken` is added in this PR. …
> fix(types): improve typing of locals

- lib/module.js
- lib/sw-templates/firebase-messaging-sw.js
- package.json
This whoud fix `const action` always refers to first item in `actions` array because:
1. `actions` item does not have `id` property but `action`, which means the `id` property value is undefined
2. `x,action` value is a string and does not have `action` property too, which means the `action` property value is undefined too
3. comparing undefined with undefined always returns true, then `action` constant will be always the first action in `actions` array
> Fix found action is always first item in `actions`

- lib/module.js
If the config doesn't include one of the required keys, you get an error message as follows: 
`ERROR  Missing or incomplete config for current environment 'development'`
This update improves the error message to include the missing key in the error so the user can address it easily without having to go look into this source code. 
The new error message is as following (when databaseURL is not included in the config): 
`ERROR  Missing or incomplete config for current environment 'development': key 'databaseURL' is required! `
> vague error message when required key is missing

- types/index.d.ts
Added type definition for $fireAuthStore as I got typescript error when I tried to use $fireAuthStore.
I'm still learning nuxt and not familiar with the community so please advise if something is not right.
> fix: add type for $fireAuthStore

- lib/plugins/services/auth.js
Hi there,
It looks like the callback for idTokenChanged was naively introduced in the module in this commit https://github.com/nuxt-community/firebase-module/commit/fcf08463621b36e597dc31d9c542c46632a5beb9#diff-3d37c994b7571c62b0cfb339a4994a7ee10e263b6c6216a3d7b0b19516f52b1d
If both authStateChanged and idTokenChanged callbacks are used, the first return prevents the second callback to be registered so the Firebase update is never propagated.
With this PR, this problem should be fixed. Feel free to ask me to update it if necessarily.
> Correctly register idTokenChanged callback

- docs/content/guide/getting-started.md
A quick update to the getting started instructions to enforce firebase version 8, this tripped me up a couple of minutes ago when getting started for the first time.
> docs: add firebase version to getting started

- types/index.d.ts
Type declarations are broken as types can not be inferred when working with firebase v9.
I've adjusted `index.d.ts` to import the types from `firebase/compat` instead of just `firebase` (deprecated).
This restores type inference when working with the module.
Fixes #601
> Import firebase type declarations from firebase/compat

- docs/content/guide/options.md
- docs/content/service-options/app-check.md
- lib/plugins/services/appCheck.js
- lib/utils/template-utils.js
- types/index.d.ts
Adds support for [Firebase App Check](https://firebase.google.com/docs/app-check).
**Note: This will currently work only on the client side.**
Enable App Check inside `nuxt.config.js`:
```js
firebase: {
...
services: {
...,
appCheck: true
}
}
```
**Options:**
```js
{
// Fill debug token to be used.
// See more https://firebase.google.com/docs/app-check/web/debug-provider
debugToken: false // default
}
```
When initialized there is possibility to activate App Check by calling 
```js
// App check works currently only on client side.
if (process.client) {
this.$fire.appCheck.activate('RECAPTCHA V3 SITE KEY')`
}
```
https://github.com/nuxt-community/firebase-module/issues/534
> feat: add support for App Check

- docs/content/guide/options.md
- lib/plugins/services/appCheck.js
- lib/utils/template-utils.js
- types/index.d.ts
- Fixed bug when `$fire.firestore.collection()` was not a function
- Added lazy load to App check library.
**Note: Use only on clientside hooks**
For example:
```js
mounted() {
this.loadAppCheck()
},
methods: {
async loadAppCheck() {
await this.$fire.appCheckReady()
await this.$fire.appCheck.activate('RECAPTCHA V3 KEY')
}
```
**or**
```js
if (process.client) {
await this.$fire.appCheckReady()
await this.$fire.appCheck.activate('RECAPTCHA V3 KEY')
}
> fix: add lazy load to app check and fix collection is not a function

- packages/docs/content/tutorials/typescript.md
Fixes a typo in the documentation page: https://firebase.nuxtjs.org/tutorials/typescript
> fix(docs): typo

- README.md
There were some grammatical errors in the README file, this PR addresses them and sends a fix
> docs: fix grammar and spelling errors in README
